name: fixngo_customer
description: >
  Official customer application for Fix-N-Go Private Limited. 
  A comprehensive mobile repair service platform providing on-demand 
  booking, real-time tracking, and secure payment solutions.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  provider: ^6.1.5+1
  flutter_stripe: ^12.6.0
  socket_io_client: ^2.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
